#!/bin/bash

function send_log() {
  CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
  KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
  TIME="10"
  URL="https://api.telegram.org/bot$KEY/sendMessage"
  TEXT="
<code>────────────────────</code>
<b>⚠️ QUOTA LIMIT REACHED FOR XRAY VMESS ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit Quota: </code><code>$total2</code>
<code>Usage     : </code><code>$total</code>
<code>────────────────────</code>
"
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function convert_bytes() {
  local -i bytes=$1
  if [[ $bytes -lt 1024 ]]; then
    echo "${bytes}B"
  elif [[ $bytes -lt 1048576 ]]; then
    echo "$(( (bytes + 1023) / 1024 ))KB"
  elif [[ $bytes -lt 1073741824 ]]; then
    echo "$(( (bytes + 1048575) / 1048576 ))MB"
  else
    echo "$(( (bytes + 1073741823) / 1073741824 ))GB"
  fi
}

while true; do
  sleep 5
  users=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
  
  if [[ ! -e /etc/limit/vmess ]]; then
    mkdir -p /etc/limit/vmess
  fi

  for user in ${users[@]}; do
    downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" 2>/dev/null | grep -w "value" | awk '{print $2}' | cut -d '"' -f2)
    if [[ -z $downlink ]]; then
      downlink=0
    fi

    if [[ -e /etc/limit/vmess/${user} ]]; then
      previous=$(cat /etc/limit/vmess/${user})
      total=$((downlink + previous))
      echo "$total" > /etc/limit/vmess/"${user}"
    else
      echo "$downlink" > /etc/limit/vmess/"${user}"
    fi
    xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
  done

  for user in ${users[@]}; do
    if [[ -e /etc/vmess/${user} ]]; then
      quota=$(cat /etc/vmess/${user})
      if [[ $quota -gt 0 ]]; then
        if [[ -e /etc/limit/vmess/${user} ]]; then
          usage=$(cat /etc/limit/vmess/${user})
          total=$(convert_bytes $usage)
          limit=$(convert_bytes $quota)
          if [[ $usage -gt $quota ]]; then
            uuid=$(grep -E "^},{" "/etc/xray/config.json" | grep -i '"'"${user}"'"' | cut -d " " -f 2 | cut -d '"' -f 2 | uniq)
            exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i '/#vmess$/a\### '"$user $exp $uuid"'' /etc/xray/.lock.db
            sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
            send_log
            rm -rf /etc/limit/vmess/${user}
            rm -rf /etc/vmess/${user}
            systemctl restart xray >/dev/null 2>&1
          fi
        fi
      fi
    fi
  done
done